#!/bin/bash

cat albums \
   | grep -o '\(\"id\":\)\(\"[0-9]*\"\)' \
   | awk -F ":" '{print $2}' \
   | sed 's/\"//g; n;d' > Album_ID_list; \

readarray -t array < <(cat Album_ID_list);

for i in "${array[@]}"; do
   wget "https://graph.facebook.com/$i/photos?access_token=$token_string" -O "Photostream_Album_$i" &&
   chmod a+rwx "Photostream_Album_$i";
   cat "Photostream_Album_$i" >> "Photostream_photos";
   done

for i in $(ls Photostream_Album*); do
   rm -r $i; 
   done 

cat Photostream_photos \
   | sed 's/,/\n/g;s/[\"}]//g' \
   | awk '/source:/ {print}' \
   | grep "\_a.jpg" \
   | sed 's/source://g' > "photo_urls";

Q=$(wc -l photo_urls | sed 's/[ a-z\_]//g');A='0'; 

array=( 'Album_ID_list' 'albums' 'Photostream_photos' 'albums' );
for i in "${array[@]}"
   do
   echo > $i
   done

while [[ A -lt $Q ]]; do 
      for i in $(cat photo_urls); do 
      wget "$i" -O "photo$A"; let A=A+1; 
      done 
   done

   mkdir -p FB_PHOTOS && 
   mv $(ls | grep "^\(photo[0-9]\)") FB_PHOTOS && rm -r $(ls | grep "^\(photo[0-9]\)");

exit 0;
